import { StyleSheet } from 'react-native';
export default StyleSheet.create({ container: { flex: 1, 
    padding: 26, 
    justifyContent: 'center' }, 
    emoji: { textAlign: 'center', 
    fontSize: 55 }, 
    title: { textAlign: 'center', 
    color: '#245A43', 
    fontSize: 29, 
    fontWeight: '900', 
    marginTop: 10 }, 
    subtitle: { textAlign: 'center', 
    color: '#72857C', 
    marginTop: 8 }, 
    card: { backgroundColor: '#FFF', 
    borderRadius: 24, 
    padding: 20, marginTop: 27 }, 
    label: { color: '#365B4B', 
    fontWeight: '800', marginBottom: 8 }, 
    input: { height: 50, borderWidth: 1, 
    borderColor: '#CFE1D4', 
    borderRadius: 13, paddingHorizontal: 14, 
    marginBottom: 20 }, 
    ages: { flexDirection: 'row', 
    justifyContent: 'space-between', 
    marginBottom: 22 }, age: { width: 42, 
    height: 42, 
    borderRadius: 21, 
    textAlign: 'center',
    textAlignVertical: 'center', 
    backgroundColor: '#F0F7EC', 
    color: '#245A43', 
    fontWeight: '900' } });
