import { StyleSheet } from 'react-native';
export default StyleSheet.create({ page: { padding: 22, 
    paddingBottom: 35 }, 
    greeting: { color: '#6F827A', fontWeight: '700' }, 
    title: { fontSize: 29, fontWeight: '900', color: '#245A43', 
    marginTop: 7 }, subtitle: { color: '#71827B', marginTop: 5,
    marginBottom: 20 },
    grid: { flexDirection: 'row',
    flexWrap: 'wrap', justifyContent: 'space-between', 
    gap: 14 }, card: { width: '47.8%', 
    height: 160, padding: 15, 
    borderRadius: 22, 
    justifyContent: 'flex-end', 
    overflow: 'hidden' }, 
    emoji: { fontSize: 63, 
    position: 'absolute', 
    top: 12, alignSelf: 'center' }, 
    cardTitle: { color: '#FFF', fontSize: 19, fontWeight: '900' }, 
    cardText: { color: '#FFF', fontSize: 12, marginTop: 2, fontWeight: '700' }, 
    tip: { marginTop: 22, backgroundColor: '#FFF3C4', borderRadius: 16, padding: 15 }, 
    tipText: { color: '#806424', fontWeight: '700', lineHeight: 20 } });
