import { StyleSheet } from 'react-native';
export default StyleSheet.create({ 
    container: { flex: 1, 
    backgroundColor:  '#DDF2C6', 
    padding: 27,
    justifyContent: 'center', 
    gap: 12 }, 
    eyebrow: { textAlign: 'center',
    color: '#55765A', 
    fontWeight: '900', 
    letterSpacing: 2,
    fontSize: 12 },
    logo: { textAlign: 'center', 
    fontSize: 45, 
    color: '#245A43', 
    fontWeight: '900' }, 
    accent: { color: '#F08D42' }, 
    scene: { backgroundColor: '#86C460',
    borderRadius: 30, 
    minHeight: 165, 
    alignItems: 'center', 
    justifyContent: 'center',
    marginVertical: 14 }, 
    trees: { fontSize: 22, marginTop: 9 }, 
    copy: { textAlign: 'center', 
    color: '#3C624D', 
    fontSize: 17, 
    lineHeight: 24, 
    marginBottom: 10 } });
